# Generated by Django 5.2.3 on 2025-07-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medEx_app', '0002_alter_patientbooking_options_patientbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbooking',
            name='visit_date',
            field=models.DateTimeField(),
        ),
    ]
