# Generated by Django 5.2.3 on 2025-07-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medEx_app', '0003_alter_patientbooking_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
