# Generated by Django 5.2.3 on 2025-07-16 21:06

from django.db import migrations

def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),  # Adjust based on your last migration
    ]

    operations = [
        migrations.RunPython(create_profiles_for_existing_users),
    ]
